// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcqohmvqoejassvrtxby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcW9obXZxb2VqYXNzdnJ0eGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTQwMDIsImV4cCI6MjA2MzE3MDAwMn0.ZznazdIAZw1vXUSgT7seT92BGQw4FTPzcS0iS629rb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);